# Generated by Django 3.2.5 on 2022-10-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user',
            new_name='username',
        ),
    ]
