# Generated by Django 3.2.5 on 2022-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=250, verbose_name='Ключевые слова')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
        ),
    ]
