# Generated by Django 3.2.5 on 2022-10-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeysWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=250, verbose_name='Ключевые слова')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='keys',
        ),
        migrations.AddField(
            model_name='quotes',
            name='keys',
            field=models.ManyToManyField(to='admininterface.KeysWords'),
        ),
    ]
