# Generated by Django 3.2.5 on 2022-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0002_auto_20221007_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyswords',
            name='keyword',
            field=models.CharField(max_length=50, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
    ]
