# Generated by Django 3.2.5 on 2022-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0003_auto_20221008_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Действие пользователя')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
